### ISSUE TITLE
Error in advlib-ble-manufacturers/lib/pur3ltd.js

### ISSUE THREAD

**Issue by m-murillo** [reelyactive/advlib-ble-manufacturers#1]
Hello reelyactive!

I was testing your code with our test codes folder and the example code in README.md and I have the same error in the example of README.md (hello advlib-ble-manufacturers) and in advlibblemanufacturers.test.js:
```/home/.../node_modules/advlib-ble-manufacturers/lib/pur3ltd.js:34
  catch {
        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/.../node_modules/advlib-ble-manufacturers/lib/advlibblemanufacturers.js:12:17)
```

I thought it was a simple error and I add to advlib-ble-manufacturers/lib/pur3ltd.js `catch (error) { console.error(error);` but it seems it isn't working.

- In the example of README.md (hello advlib-ble-manufacturers) it returns `null`.
- In advlibblemanufacturers.test.js:
```/home/.../node_modules/advlib-ble-manufacturers/test/unit/advlibblemanufacturers.test.js:29
describe('advlib-ble-manufacturers', function() {
^

ReferenceError: describe is not defined
    at Object.<anonymous> (/home/.../node_modules/advlib-ble-manufacturers/test/unit/advlibblemanufacturers.test.js:29:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

I'm running the scripts in Ubuntu 18.04.6 LTS with the cmd commands and I have node v8.10.0. Maybe I'm doing something wrong because I haven't so much experience in this.

Thank you.

**Comment by m-murillo** [comment]
Hello.

I updated the node v8.10.0 to v16.18.0.

I still have the same errors without the code I added before.
-

**Comment by m-murillo** [comment]
Hello.

By mistake I closed the issue, sorry.

I updated the node v8.10.0 to v16.18.0.

I still have the same errors without the code I added before.
- In the example of README.md (hello advlib-ble-manufacturers) it returns `null`.
- In advlibblemanufacturers.test.js:

```/home/.../node_modules/advlib-ble-manufacturers/test/unit/advlibblemanufacturers.test.js:29
describe('advlib-ble-manufacturers', function() {
^

ReferenceError: describe is not defined
    at Object.<anonymous> (/home/.../node_modules/advlib-ble-manufacturers/test/unit/advlibblemanufacturers.test.js:29:1)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```

Thank you.

**Comment by m-murillo** [comment]
Hello again!

I was watching where was the mistake in the example of README.md (hello advlib-ble-manufacturers) and it's on `function processIBeacon` (/home/.../node_modules/advlib-ble-manufacturers/lib/apple.js:75). It seems the variable `isInvalidLength = true` because:

```
let isInvalidLength = (data.length !== IBEACON_FRAME_LENGTH) || //22 !== 23 (true)
                                 (data.readInt8(FRAME_LENGTH_OFFSET) !== IBEACON_LENGTH); // 0 !== 21 (true)
if(isInvalidLength) {
    return null;
}
```

So it returns null in consequence. 
Sorry if I split the problem, but I'm working on it.

Thank you.

**Comment by jeffyactive** [comment]
Hi @m-murillo, you have indeed found a problem with the example on the README.md: the `manufacturerData` variable was missing a byte, and hence the library returned `null` when processing, as it should.  Sorry for the trouble this has led you to!

The example on the README.md has been updated, and with the updated `manufacturerData` you should see an output of:

```
{
  deviceIds: [ '00112233445566778899aabbccddeeff/0123/4567' ],
  txPower: -4,
  uri: 'https://sniffypedia.org/Organization/Apple_Inc/iBeacon/'
}
```

Please confirm and close the issue if that works for you.  Note that you may wish to instead use [advlib](https://github.com/reelyactive/advlib) with advlib-ble-manufacturers as a library, as this is the more common use case.  Thanks!

**Comment by m-murillo** [comment]
Hello jeffyactive!

It works, thank you so much.
